"""updated user table

Revision ID: 1c527009be3a
Revises: 
Create Date: 2026-07-26 20:44:46.718927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c527009be3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_profiles', 'total_orders',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_profiles', 'failed_deliveries',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_profiles', 'failure_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_profiles', 'failure_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('customer_profiles', 'failed_deliveries',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer_profiles', 'total_orders',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
