"""add rider operational location and area performance

Revision ID: 887c096a1fc8
Revises: 24f6bd4d34be
Create Date: 2026-08-15 11:15:40.137782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887c096a1fc8'
down_revision: Union[str, Sequence[str], None] = '24f6bd4d34be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_area_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('successful_deliveries', sa.Integer(), nullable=False),
    sa.Column('failed_deliveries', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_area_performance_area'), 'rider_area_performance', ['area'], unique=False)
    op.create_index(op.f('ix_rider_area_performance_id'), 'rider_area_performance', ['id'], unique=False)
    op.create_index(op.f('ix_rider_area_performance_rider_id'), 'rider_area_performance', ['rider_id'], unique=False)
    op.alter_column('predictions', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('riders', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('riders', sa.Column('current_longitude', sa.Float(), nullable=True))
    op.add_column('riders', sa.Column('last_location_update', sa.DateTime(), nullable=True))
    op.alter_column('riders', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('riders', 'max_orders_per_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('riders', 'current_order_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('riders', 'completed_orders',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('riders', 'failed_deliveries',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('riders', 'failed_deliveries',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('riders', 'completed_orders',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('riders', 'current_order_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('riders', 'max_orders_per_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('riders', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('riders', 'last_location_update')
    op.drop_column('riders', 'current_longitude')
    op.drop_column('riders', 'current_latitude')
    op.alter_column('predictions', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_rider_area_performance_rider_id'), table_name='rider_area_performance')
    op.drop_index(op.f('ix_rider_area_performance_id'), table_name='rider_area_performance')
    op.drop_index(op.f('ix_rider_area_performance_area'), table_name='rider_area_performance')
    op.drop_table('rider_area_performance')
    # ### end Alembic commands ###
