"""add category table

Revision ID: 8d2dc8100c41
Revises: b2a4d1676ce5
Create Date: 2026-08-07 07:37:33.723818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2dc8100c41'
down_revision: Union[str, Sequence[str], None] = 'b2a4d1676ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_category_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_category_id_fkey'), 'items', 'order_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
