"""changed the model as of customer and order update

Revision ID: ae90a828f5a5
Revises: fcaebe2a92f6
Create Date: 2026-08-06 12:32:43.484374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae90a828f5a5'
down_revision: Union[str, Sequence[str], None] = 'fcaebe2a92f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('failed_deliveries', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('unreachable_count', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('total_orders', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('is_cod', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'is_cod')
    op.drop_column('orders', 'risk_score')
    op.drop_column('customers', 'total_orders')
    op.drop_column('customers', 'unreachable_count')
    op.drop_column('customers', 'failed_deliveries')
    # ### end Alembic commands ###
