"""updated the calculate_risk with DB changes

Revision ID: b2a4d1676ce5
Revises: ae90a828f5a5
Create Date: 2026-08-06 16:08:05.010936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a4d1676ce5'
down_revision: Union[str, Sequence[str], None] = 'ae90a828f5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
