"""added created_at to customers

Revision ID: fcaebe2a92f6
Revises: 3ff971afd007
Create Date: 2026-08-06 11:17:16.272811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaebe2a92f6'
down_revision: Union[str, Sequence[str], None] = '3ff971afd007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'created_at')
    # ### end Alembic commands ###
